services:
  enu-website:
    image: ghcr.io/xgenya/enu-website:latest
    pull_policy: always
    container_name: enu-website
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
